### ISSUE TITLE
[BUG] Checkbox required rule does not work

### ISSUE THREAD

**Issue by basvandertogt** [laraform/laraform#132]
### Prerequisites

* [X] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [X] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration - all with full class).
* [X] Your issue isn't already filed.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.4.5
* Laravel version: 5.6
* Laraform Vue package version and type: 1.2.9 Pro
* Laraform Laravel package version: 1.2.2

### Description

The required rule does not work on a checkbox element.

### Steps to Reproduce

```
'conditions' => [
    'type' => 'checkbox',
    'text' => 'Voorwaarden',
    'trueValue' => 1,
    'falseValue' => 0,
    'rules' => ['required']
],
```

**Expected behavior:**

It should give an error when submitting the step or form.

**Actual behavior:** 

It validates and does not give an error.

**Comment by adamberecz** [comment]
You should use [`accepted`](https://laraform.io/docs/1.x/basics/validation#rule-accepted) rule for checkboxes instead of `required`. Required only invalidates primites for `null`, `undefined` and empty string on both [backend](https://laravel.com/docs/8.x/validation#rule-required) and [frontend](https://laraform.io/docs/1.x/basics/validation#rule-required).

**Comment by basvandertogt** [comment]
Ok thank you. This works!
