### ISSUE TITLE
[QUESTION] Can we use laraforms with normal blade/laravel-livewire templating?

### ISSUE THREAD

**Issue by jechaviz** [laraform/laraform#142]
I don't know if it's posible use simple blade or https://laravel-livewire.com with laraform?

Thank you.

**Comment by adamberecz** [comment]
I've just got this question in an email too. Here's my reply: what Laraform's backend package does is basically rendering a Vue component with a :form property that contains all the information you define in the backend form class (schema, wizard, buttons, etc.). It also provides a couple of endpoints to process data. So the actual job on the frontend is done by the Vue component and because of that I'm not sure if Laravel-Livewire is something that would make sense to use.
