### ISSUE TITLE
[QUESTION] Easier way to translate multi-select "Options Selected" text

### ISSUE THREAD

**Issue by PunchRockgroin** [laraform/laraform#149]
* [x] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [x] Your question isn't already asked before.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.4.2
* Laravel version: 8.22.1
* Laraform Vue package version and type: 1.2.2 pro
* Laraform Laravel package version: 1.2.2 pro

### Description

Is there a better way of setting/translating the "X options selected" text in multi-select fields?

### Additional Information

I could not get the I18n to catch the content "X options selected" text in multi-select fields, and I need to change "X options selected" anyway when there is 1 option selected in a multi-select list -- "1 options selected" is getting called out by my messaging team for the improper plural of "option".

I can perform a text modification and translations on the vue-multi-select selection slot by passing along the translations using the $with method to set "selectOptionsTranslations" on the Laravel side, then creating a OptionsSelectedComponent component  which gets that information from this.el$.form$.selectOptionTranslations and set that to the selection slot in as described in https://laraform.io/docs/1.x/reference/multiselect-element#slot-selection

Feels like this is a lot, and I just want to make sure I'm doing the correct thing. If there is no current way of doing it differently, it would be nice to be able to set these on the Laravel end especially when I have many multi-select fields to set this to. Something that could be set globally.

Thanks!

**Comment by adamberecz** [comment]
In the future this won't require any manual hassle because the the multiselect tag will be grammatically correct even for singular value (as we are moving away from `vue-multiselect` to custom library). Right now unfortunately that's the way to go. I'm wondering if [overriding](https://laraform.io/docs/1.x/how-tos/creating-element#override-existing-element) the multiselect element could save you the trouble of manually setting the slot for each case. It's actually quite straightforward:
1) Create `MultiselectElement.vue` in your project
2) Copy the contents from `@laraform/laraform/src/themes/default/components/elements/SelectElement.vue`
3) Replace `script` with this:
```vue
<script>
  import MultiselectElement from '@laraform/laraform/src/components/elements/MultiselectElement'

  import Multiselect from 'vue-multiselect/src'

  export default {
    mixins: [MultiselectElement],
    components: {
      Multiselect,
    },
  }
</script>
```
(you might need to install `npm i vue-multiselect`)
4) Replace `selection` slot with the value you want (eg. `el$.form$.selectOptionTranslations`)
5) Override `multiselect` element before install:
``` js
import Vue from 'vue'
import Laraform from '@laraform/laraform'
import MultiselectElement from './path/to/my/MultiselectElement.vue'

Laraform.element('multiselect', MultiselectElement)

Vue.use(Laraform)

const app = new Vue({
  el: '#app'
})
```

Should work.
