### ISSUE TITLE
Support !!! [BUG]

### ISSUE THREAD

**Issue by mizbanpaytakht** [laraform/laraform#189]
NO SUPPORT !

**Comment by adamberecz** [comment]
Is there a question?

**Comment by adamberecz** [comment]
@mizbanpaytakht looked up our spam folder and found your email. Here's how you can ignore a field from being saved:
https://laraform.io/docs/1.x/reference/frontend-element#option-submit

```php
'field' => [
  'type' => 'text',
  'submit' => false
]
```

I hope your future emails won't be marked as spam but if they do and you don't receive an answer from our support in a couple of days please go ahead and post the issue here.

**Comment by mizbanpaytakht** [comment]
Thankyou @adamberecz , I have another problem related to inserting data by using AutoProcess method.
for multiply choices, group inputs, and files I choose array type for field model cast.
There is a problem when I have a file field in a form with wizard the file field is not listed in attributes,however, file is uploaded successfully and record is created in db but without the file field.

`
exception: "Error"
file: "vendor/laraform/laraform-laravel/src/Database/Strategies/ListStrategy.php"
line: 49
message: "Attempt to assign property \"photo\" on null"
`

The ```$target``` variable only carries fields for the wizard step1.

**Comment by adamberecz** [comment]
Please create a new issue for this with a reproducible example (in compliance with the issue template) so that I can look into it.
