### ISSUE TITLE
[QUESTION] Button options

### ISSUE THREAD

**Issue by romeosemper** [laraform/laraform#29]
### Prerequisites

* [X] You've read the [documentation](http://laraform.io/docs) and couldn't find an answer.
* [X] Your question isn't already asked before.
* [X] You filled in the entire issue template.

### Versions

* PHP version: 7.4
* Laravel version: 6.6
* Laraform Vue package version: 1.1.8 (Pro)
* Laraform Laravel package version: 1.1.8 (Pro)

### Description

A few question about buttons:

* Is it possible to create multiple button groups with different positions in the DOM? (for example 2 buttons on top of the form, one on the bottom)
Actually the position in the DOM would not even have to change, it would just be nice to configure the buttons-container class per group and not only per form.

* Is there a way to use icons (FontAwsome) within buttons, or to use HTML within the label?

* Are conditions possible? (usefull, if the button availability depends on the users permissions)

### Additional Information

None

**Comment by laraform** [comment]
Built in buttons does not support these at the moment, but you can disable them conditionally:
(2nd example) https://laraform.io/docs/1.x/basics/buttons#extending-on-frontend

I'd recommend creating your own implementation of buttons to cover these use cases. Just create a custom Laraform component which uses Laraform mixin, then override the template, based on `@laraform/laraform/src/components/Laraform.vue` and add your custom buttons component instead of the built in ones.

Buttons are quite low level, shouldn't be too much hassle to create a custom solution. I did save your thoughts on this one and will keep them in mind when touching this part next time.

**Comment by romeosemper** [comment]
Yes you are right, its quite easy to just overwrite it. 
Thanks for the tipp!
