### ISSUE TITLE
"export 'extendTheme' was not found in '@laraform/laraform/src/utils'

### ISSUE THREAD

**Issue by tanthammar** [laraform/laraform#31]
I am trying to follow your documentation for extending the default theme

Error on compilation with Laravel Mix:
``` 
"export 'extendTheme' was not found in '@laraform/laraform/src/utils'
``` 

resources/js/laraform/theme/index.js
```js
import { extendTheme } from '@laraform/laraform/src/utils'
import defaultTheme from '@laraform/laraform/src/themes/default'

export default extendTheme(defaultTheme, {
  classes: {},
  elements: {},
  components: {},
  layouts: {},
  grid: {},
})
```

**Comment by laraform** [comment]
Hi! The docs was wrong, thank you for reporting. See the updated version:
https://laraform.io/docs/1.x/how-tos/creating-theme#creating-theme-file

**Comment by iSWORD** [comment]
Any idea how to do these imports in community edition?

```javascript
import utils from '@laraform/laraform/src/utils'
import bs4 from '@laraform/laraform/src/themes/bs4'
```

How come this is released under a GPL license but the source code is compiled / uglified? 🤔 

I've been trying to get this to work in a modular Laravel 7 project with Vue router before asking the company I work for to purchase a Laraform license, but so far this has been a very unpleasant experience on so many levels. All links to docs seem to have changed. Everything doesn't work as expected, even github issues don't have descriptive titles (but I can only blame the community for this one). I spent almost 6 hours just trying to get the very basic hello world example to work in my project and ended up doing too much digging & hacking, and now I'm worried that future updates could break my "hacks".

I don't mean to discourage you at all, Adam, this seems to be a **very** cool project, and I wouldn't have bothered spending all this time trying to get it to work if I didn't believe in its potential, but I just want you to understand that the way many things don't work as expected is very frustrating for new customers, and you need to do something about it.

**Comment by iSWORD** [comment]
@laraform

**Comment by laraform** [comment]
Yeah that experience does sound terrible, very sorry about that and thank you for sharing it. Only these kind of feedback can reveal if there's something wrong - which feels bad of course, but unfortunately it's part of the process. 

Well, regarding GPL, I know it's not the best but until we have our custom EULA for the free version too that was the closest that we wanted to have. The point of this version is btw to evaluate how you could use Laraform within your project - a sort of demo. But you're right that we should be more explicit about what's included in the free version and what's not. Eg. extending themes is not possible right now, because it relies on full source code (`src` folder) - I'll make sure these will be added in the future.

Nevertheless I'm glad you see value in Laraform, but again, sorry about the bad initial experience. If you haven't fully lost you motivation and still interested in giving Laraform a shot, reach out to me in email (adam x laraform.io) and I'll set up a special discount code to make it up for the inconvenience. We also have the 14 day money-back thing so if Laraform still does not satisfies you needs you get it back - no questions asked. I'm really not trying to talk you into a purchase but I'm confident with full version you'll have no trouble using Laraform at all.

ps: if you've found a broken docs link in the site please report. We had a complete update recently and that could caused some troubles although I'm not aware of any at the moment.

**Comment by iSWORD** [comment]
Thanks a lot Adam for understanding and for your professional response. Also thank you for offering the special discount. I really appreciate it.

Unfortunately for me, I will have to revert my changes since I needed to implement part of the frontend for the project and demo it before deciding on buying a license, and I can't do that without applying the project's theme. I remember reading somewhere that the free edition only lacked some additional components so I thought I'd do free then upgrade if Laraform proves to improve my workflow. I might still revisit Laraform in a future project, or hack my way around with plain CSS before my demo and see how it goes.

As for the docs links, I haven't found broken links on the website itself but all links posted on Github including the one in [your comment](https://github.com/laraform/laraform/issues/31#issuecomment-566951689) from December above don't work.

Thanks again & have a great day.
