### ISSUE TITLE
List, not showing default values

### ISSUE THREAD

**Issue by gmartinez** [laraform/laraform#5]
I am defining a form in the backend, following the documentation I have

            '_props->todo'=> [
                'type'=> 'list',
                'label'=> 'To-do',
                'element'=> [
                  'type'=> 'text',
                  'placeholder'=> 'Write here...'
                ],
                'default'=> [
                  'Write docs',
                  'Create unit tests',
                  'Set up npm',
                ]
            ]

as part of the array to be returned by the schema() function.

The control gets draw in the screen, but empty, that is the default values are not shown.

Any idea ?

**Comment by gmartinez** [comment]
Also, upon submitting I get;

>exception: "ErrorException" file: "{...}\vendor\laraform\laraform-laravel\src\Elements\ListElement.php"
line: 135
message: "Invalid argument supplied for foreach()"

inspecting the generated form html I see that entries in the list gets generated with a simple numeric name and id, eg;

> &lt;input name="0" id="0" placeholder="Write here..." autocomplete="true" type="text" class="form-control"&gt;

**Comment by laraform** [comment]
Hi @gmartinez! Which version are you using? Current Pro is 1.1.5 for Vue and 1.1.4 for Laravel, please try updating. I suspect this is a bug from an earlier version, because in the latest it's working as expected with the schema you've sent.

**Comment by gmartinez** [comment]
Any way better than other to check versions installed ?

File node_modules/@laraform/laraform/package.json starts with;

> {
  "_from": "@laraform/laraform@1.1.5",
  "_id": "@laraform/laraform@1.1.5",
  ...

while file vendor/laraform/laraform-laravel/src/copmoser.json stats with;

> {
    "name": "laraform/laraform-laravel",
    "description": "Laraform Laravel package",
    "version": "1.1.4",

In both cases though the corresponding changelog.log files states;

> Laraform (laraform-laravel) 1.1.0
Release date: 2019-06-30

FYI, I initially installed community version and upon purchase followed the upgrade to premium instructions.

!?

**Comment by gmartinez** [comment]
Sorry, I forgot to mention, I run both composer and npm updates and none related to laraform came through.

**Comment by laraform** [comment]
The change.log is just a remain from the earlier change log tracking and will be remove in next patch. For the latest versions and their updates always refer to: https://laraform.io/releases. 

I can see that you are using the latest versions, so that's not the problem. Could you share your whole form class?

Also what you can try is to remove the node_modules and vendor folders then reinstall after also removing anything related to Laraform's community version (only leaving pro). They should not interfere, but it's not impossible.

**Comment by gmartinez** [comment]
I took node_modules/@laravel folder to a temporary location, run npm update to reinstall, no luck (newly installed form has the exact same as the one I moved to temp location).

Find attached users.zip with.
[User.zip](https://github.com/laraform/laraform/files/3671736/User.zip)

**Comment by laraform** [comment]
So far I'm not able to reproduce the bug, even from the schema you've sent - it's working as expected on my end. We need to dig deeper, so please also send:
- composer.json
- package.json
- your main app.js file where Laraform is imported
- the 'generic-form' Vue component that the form you've sent is using.

**Comment by gmartinez** [comment]
Sorry it took me few hours to get back to you, based on your last comment I preferred to take the time to do some further testing on my side, here are my findings;

1. Seems I might have misunderstood the concept of "defaults", my initial take was that when editing an existing record and while loading the record (form) data using setData() method, if a particular key did not exist the defaults were going to kick in, apparently setData() overwrites all and therefore no defaults are shown in such case.

2. I've also reported (I initially thought related) that upon trying to save the form when it contained a list, I got "Invalid argument supplied for foreach()" in line 135 of "{...}\vendor\laraform\laraform-laravel\src\Elements\ListElement.php".

I found that in my case $originalCollection was getting null, so the way I found to have this working was to change the input of the foreach to; "$originalCollection ?? []". With this change, simple lists works.

My guess about this variable getting null is that I am referencing properties of a database json column, so "$originalCollection = $entity->{$this->attribute};" probably does not handle well the extra "->"

I am realizing that I did not explicitly mentioned that some of my input is expected to be read/written in a json column, maybe this is not all that supported/tested ? seems to be working so far but I guess there might be nuances.

Thoughts ?

**Comment by laraform** [comment]
You are very right and that "?? []" is exactly the missing piece. It should also make a type check so that accidental JSON strings don't get stuck. When using JSON string on the database level make sure to cast them to array or transform them manually with mutators/accessors. I've added the fix and will be release with the next patch. 

As for the defaults: when loading data for the form, it will use the [.load()](https://laraform.io/docs/1.x/reference/frontend-form#method-load) method on the frontend, which in fact eliminates all the default values. The [.update()](https://laraform.io/docs/1.x/reference/frontend-form#method-update) method can be used to avoid overriding defaults but that requires custom data handling.

**Comment by gmartinez** [comment]
Glad that helped.

I'll proceed to close this ticket (I have some other issue around the list control when using "object" but I'll report that separately).
